### PR TITLE
Fixup: Add action.sh support

### PR DESCRIPTION
**Pull request by selfmusing**
- Using curl to fetch pif.json
- Included killall command as well to apply the new pif.json

### CODE REVIEW

**Comment by selfmusing** [comment]
Here's how it works : https://drive.google.com/file/d/1AWAZVzdG5C5I1zcQd0HsEWFwcFD88xCN/view

**Comment by chiteroman** [comment]
Magisk includes curl binary ?

**Comment by selfmusing** [comment]
> Magisk includes curl binary ?

Someone told me that it's working for me only because some custom roms include curl binary by default.
Still have to confirm, if it works for oem users or not.

**Comment by NBruderman** [comment]
Or you can just use the autopif2.sh script from @osm0sis fork, which just auto generate pifs from the latest android beta

**Pull request closed without merging**
