### PR TITLE
Added troubleshooting section to readme

### PR DESCRIPTION
**Pull request by XantreGodlike**
This methods helped me and some people, so I've decided to add it to readme
https://t.me/playintegrityfix/1232
https://t.me/playintegrityfix/1346

### CODE REVIEW

**Comment by VisionR1** [comment]
Yeah, this i have write before but my README.md ignored

IMG_20231121_230727

**Comment by XantreGodlike** [comment]
I think it should be the steps only in case of troubleshooting. Because at some time it worked without this steps

**Comment by VisionR1** [comment]
> I think it should be the steps only in case of troubleshooting. Because at some time it worked without this steps

Yeah i think if waiting some hours without delete cache and data, is work and the Google play store show again apps (Netflix) etc.

**Comment by chiteroman** [comment]
Thanks ❤

**Pull request merged**
