### PR TITLE
custom.pif.json check, use and restore; enable custom branch module updates, and more (custom)

### PR DESCRIPTION
**Pull request by osm0sis**

### CODE REVIEW

**Comment by osm0sis** [comment]
I *think* this should work, busy day so haven't built it yet. 😬🤞

**Comment by osm0sis** [comment]
I chose to use stat since it's supposed to be fastest from what I read, but in case there is a problem with using it, this would be the alternative:

https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/page-176#post-89189347

**Review by chiteroman — CHANGES_REQUESTED** [review]
```cpp
    struct stat tmpbuf;
    if (stat(CUSTOM_JSON_FILE_PATH, &tmpbuf) == 0) {
       FILE *json = fopen(CUSTOM_JSON_FILE_PATH, "r");
    else {
       FILE *json = fopen(JSON_FILE_PATH, "r");
    }
```

What is this ?

Also, why get so complicated by creating two different files... It's best to have it all in one, so there's less hassle. What could be done is to include several fingerprints within the same pif.json file.
Another thing, why use stat when in C++ you have std::filesystem::exists ? As long as you don't use fstream or sstream everything will be fine, (those two headers add 100KB to the final library...)

**Comment by chiteroman** [comment]
```json
{
  "USE": 0,
  "DATA": [
    {
      "PRODUCT": "taimen",
      "DEVICE": "taimen",
      "MANUFACTURER": "Google",
      "BRAND": "google",
      "MODEL": "Pixel 2 XL",
      "FINGERPRINT": "google/taimen/taimen:8.1.0/OPM4.171019.021.R1/4833808:user/release-keys",
      "SECURITY_PATCH": "2018-07-05",
      "FIRST_API_LEVEL": "25"
    },
    {
      "PRODUCT": "asd",
      "DEVICE": "asd",
      "MANUFACTURER": "Google",
      "BRAND": "google",
      "MODEL": "asd",
      "FINGERPRINT": "swfqwergqwe",
      "SECURITY_PATCH": "2018-07-05",
      "FIRST_API_LEVEL": "32"
    }
  ]
}
```

Something like this.

**Comment by osm0sis** [comment]
How you want to check for the file is another thing, do it however you like. As I said, I'd read that stat was faster.

**Comment by osm0sis** [comment]
arda99's suggestion of

```
FILE *json = fopen(CUSTOM_JSON_FILE_PATH, "r");
if (!json)
   json =  fopen(JSON_FILE_PATH, "r");
```
Would be nice and simple if you'd like me to switch it to that.

**Pull request merged**
