### PR TITLE
Move early props to post-fs-data.sh, warn about deprecated/conflicting MHPC module (main)

### PR DESCRIPTION
**Pull request by osm0sis**

### CODE REVIEW

**Comment by chiteroman** [comment]
Some users use MagiskHidePropsConf to spoof specific props for their system. Instead force remove it, I think it's better to just warn the user about it.

**Review by chiteroman — CHANGES_REQUESTED** [review]
Just force remove safetynet-fix.

If user has MagiskHidePropsConf installed, should warn about it.

**Comment by osm0sis** [comment]
> Just force remove safetynet-fix.
> 
> If user has MagiskHidePropsConf installed, should warn about it.

I can change that if you like, but arguably they should find a new way to do that since MPHC is extremely unmaintained and deprecated, and blocking it would be for the best.

It's super simple just to make your own system.prop in a basic Magisk module, for example.

**Comment by osm0sis** [comment]
arda99's suggestion of

```
FILE *json = fopen(CUSTOM_JSON_FILE_PATH, "r");
    if (!json)
       json =  fopen(JSON_FILE_PATH, "r");
```
Would be nice and simple if you'd like me to switch it to that.

**Pull request merged**
